// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// import EmptyStateController from "./empty_state_controller"
// application.register("empty-state", EmptyStateController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)
